# Generated by Django 4.2.16 on 2024-10-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nome',
        ),
    ]
